### PR TITLE
Fix display of empty headers on iOS 11

### LINKED ISSUE #105: Blank section headers are displayed under iOS 11
It looks like blank section headers/footers are being shown on devices running iOS 11 (as of beta 2) when a `Section` is initialized with `nil` as a header/footer extremity.

The below screenshots were taken with the example project after changing the value of the `header` parameter of the first section to `nil`.

| iOS 10 | iOS 11 |
| ------ | ------ |
| screen shot 2017-06-29 at 4 10 41 pm | screen shot 2017-06-29 at 4 10 39 pm |

### PR DESCRIPTION
**Pull request by nealyoung**
Makes `viewHeight` on `Extremity` non-optional and nil-coalesces to a height of 0 for `nil` section extremities - fixes #105.

### CODE REVIEW

**Comment by hyperspacemark** [comment]
Looks good to me. @nealyoung Would you mind adding some before and after screenshots to this PR for posterity?

File: Static/Section.swift [hunk 1]
```diff
@@ -27,8 +27,11 @@ public struct Section: Hashable, Equatable {
             }
         }
 
-        var viewHeight: CGFloat? {
-            return _view?.bounds.height
+        var viewHeight: CGFloat {
+            switch self {
+            case .title: return UITableViewAutomaticDimension
+            case .view(let extremityView): return extremityView.bounds.height
```
Comment (dmiluski) [inline Static/Section.swift]: This now loses auto-sizing for view extremities does it not?

**Review by 641210 — COMMENTED** [review]
image
